- addon/authenticators/oidc.js
If a session is restored but the token is still valid, no refresh loop is started to prevent a
infinite token refresh loop on multiple tabs. This token is never checked again so we never start a
refresh loop even if the token is already exipred. This causes the next request to return a 401 and
invalidates the session.
> fix(authenticators/oidc): prevent random logout

- .travis.yml
- CHANGELOG.md
- addon/authenticators/oidc.js
- addon/config.js
- addon/mixins/oidc-authentication-route-mixin.js
- config/ember-try.js
- tests/dummy/config/environment.js
- tests/dummy/mirage/config.js
- tests/unit/authenticators/oidc-test.js
Remove the keycloak specific `realm` config option since this is not a OIDC standard. The `realm` option should be part of the `host` configuration.
Further fixed the existing tests and started a change log.
> Remove keycloak specific configuration option

- CHANGELOG.md
- addon/authenticators/oidc.js
- addon/config.js
- addon/mixins/oidc-authentication-route-mixin.js
- tests/dummy/config/environment.js
- tests/dummy/mirage/config.js
- tests/unit/authenticators/oidc-test.js
- tests/unit/mixins/oidc-authentication-route-mixin-test.js
Add the `scope` parameter to the authentication request as this is required by OIDC. Also get the user information from the `userinfo` endpoint and not by parsing the `access_token`.
> Add `scope` and access `userinfo` endpoint

- addon/authenticators/oidc.js
- addon/config.js
- addon/mixins/oidc-application-route-mixin.js
- addon/mixins/oidc-authentication-route-mixin.js
- addon/mixins/oidc-end-session-route-mixin.js
- tests/dummy/config/environment.js
- tests/unit/mixins/oidc-end-session-route-mixin-test.js
* Rename config param `logoutEndpoint` to `endSessionEndpoint`
* Add new config param `afterLogoutUri`
* Add new mixins `oidc-end-session-route-mixin` and `oidc-application-route-mixin`
* Correctly handle invalidate
* Remove multiple redirects after successful authentication (fixes ember `handlerInfo` bug)
> Implement invalidate with end-session according to the OIDC specs

- addon/authenticators/oidc.js
- tests/unit/authenticators/oidc-test.js
At the moment the restore call always makes a refresh request,
which then updates the session. A session update triggers the
restore call (if not done by this exact restore call) which leads
to a infinite request loop a soon as two or more tabs of the app
using this addon are open.
To fix this the restore call only makes a refresh request if the
token actually expired. Otherwise just schedule a refresh which will
then make the actual refresh request.
> Rework restore call

- addon/authenticators/oidc.js
- addon/mixins/oidc-authentication-route-mixin.js
- addon/mixins/oidc-end-session-route-mixin.js
- addon/utils/absoluteUrl.js
- tests/unit/utils/absoluteUrl-test.js
At the moment the host url defined in the config file needs to be
absolute (http://myhost/oidc). Now it is possible to use a relative
url (/oidc) which then automatically will be extended with the
current location protocol and host.
> Allow the use of a relative host url

- addon/mixins/oidc-authentication-route-mixin.js
- tests/unit/mixins/oidc-authentication-route-mixin-test.js
This is necessary because of a change in the router_js library which
transforms Transition.queryParams into a symbol
https://github.com/tildeio/router.js/commit/a481f0acbe7275e8309867046f1e89941ff70f6a#diff-7da86d75fbaeb445442c6dd0697adc39
> fix: Fix accessing of query parameters in the authentication route

- addon/mixins/oidc-authentication-route-mixin.js
- tests/unit/mixins/oidc-authentication-route-mixin-test.js
`ember-simple-auth` handles attempted transitions which are aborted by
the authentication process. Since the oidc addon redirects the page, the
attempted transition is lost and the user will always end up on the
index (or `routeAfterAuthentication`) page. This update will store the
attempted transition and recreate it after a successful login.
> feat: handle `attemptedTransition`

- README.md
- addon/mixins/oidc-authentication-route-mixin.js
- tests/dummy/config/environment.js
- tests/unit/mixins/oidc-authentication-route-mixin-test.js
This allows "hinting" a specific identity provider to the authentication
server.
Example: Upon opening the app at http://my-app.com?login_hint=myidp
will automatically use the specified IDP (in this case "myidp") if not logged in.
This also adds a new config option "loginHintName" that allows using a
different parameter name (e.g. Keycloak's `kc_idp_hint`).
> feat(redirect): add support for login_hint

- tests/dummy/app/routes/oidc.js
The dummy app was not adapted to the transition changes in which the
queryParams are set on `transition.to` instead of `transition` directly. Add
the correct handling for both cases.
> fix(dummy-app): fix handling of `queryParams` in dummy

- addon/authenticators/oidc.js
Currently if a retry fails, `undefined` is set as the session as we do
not return anything in case we start a retry. Now the retries are
blocking and the session is ONLY set if either a retry is successful or
the last retry fails.
> fix(authenticator): await successful retry before setting the session

- addon/mixins/oidc-authentication-route-mixin.js
Without this change setting the property `authenticationRoute` (from http://ember-simple-auth.com/api/classes/AuthenticatedRouteMixin.html) on has no effect.
> Allow custom authenticationRoute / redirectUri

- .travis.yml
- package.json
BREAKING CHANGE: Node version 8.x is not supported anymore since it's
not a maintained LTS version.
> feat: remove support for node 8

- .editorconfig
- .eslintrc.js
- .github/workflows/test.yml
- config/ember-try.js
- package.json
- testem.js
- tests/dummy/config/ember-cli-update.json
- tests/unit/mixins/oidc-application-route-mixin-test.js
- yarn.lock
BREAKING CHANGE: Support for the old ember LTS 3.8 is dropped
> chore(deps): update ember and other dependencies

- README.md
- addon/authenticators/oidc.js
- addon/mixins/oidc-application-route-mixin.js
- addon/utils/absoluteUrl.js
- tests/unit/utils/absoluteUrl-test.js
Until now, all the configuration endpoints would have been appended to
the host. Now the endpoints can be absolute URLs as well. This is needed
since various OIDC providers (e.g Azure) host certain endpoints on
another host than the auth urls.
Also this fixes the `getAbsoluteUrl` util for SSL urls.
This closes #189
> fix(config): allow configuration URLs to be absolute and relative

- addon/mixins/oidc-adapter-mixin.js
The computed property `headers` was watching the `session.isAuthenticated` property which does not change when a successful token refresh happend. This lead to an error since after the
refresh the `headers` property still returned the old token.
To fix this watch the `session.data.authenticated.id_token` as according
to the openid-connect specification (https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) the `id_token` must always be present.
> fix(mixin): correctly recompute `headers` in the `oidc-adapter-mixin`

- addon/authenticators/oidc.js
- addon/mixins/oidc-authentication-route-mixin.js
- tests/dummy/config/environment.js
In ember-simple-auth 3 the configuration option `authenticationRoute`
was removed. Adjust the oidc addon so it works with ember-simple-auth 3
and previous versions. Only the `redirectUri` parts needed to be changed
for this, which was handled a bit strangly from the beginning anyway.
> feat: add support for ember-simple-auth 3

- README.md
- addon/authenticators/oidc.js
- addon/index.js
- addon/mixins/oidc-application-route-mixin.js
- addon/services/session.js
- app/services/session.js
- package.json
- tests/dummy/app/adapters/application.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/models/user.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/protected/secret.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/protected/secret.hbs
- tests/dummy/mirage/config.js
- tests/unit/authenticators/oidc-test.js
- tests/unit/mixins/oidc-application-route-mixin-test.js
There is a difference between a logout of the current application and a
logout on the authorization server. Until now the addon assumed if the
ember-simple-auth session is invalidated it should also call the
`end-session` endpoint of the authorization server which invalidates all
ongoing sessions in possible different applications. With the
introduction of the `singleLogout` function the application using this
addon can decide between invalidating the current ember-simple-auth
session or doing a global/single logout in addition.
> feat(single-logout): separate session invalidate and oidc logout

- README.md
- addon/adapters/oidc-json-api-adapter.js
- addon/adapters/oidc-rest-adapter.js
- app/adapters/oidc-adapter.js
- app/adapters/oidc-json-api-adapter.js
- app/adapters/oidc-rest-adapter.js
- tests/dummy/app/adapters/application.js
- tests/unit/adapters/oidc-json-api-adapter-test.js
- tests/unit/adapters/oidc-rest-adapter-test.js
BREAKING CHANGE: Include an adapter subclass of the Ember
RestAdapter to handle OIDC token refreshes and unauthorized
request handling. The existing OIDCadapter is renamed to
OIDCJSONAPIAdapter to clarify the base class origin.
> feat(adapter)!: add oidc rest adapter and refactor adapter naming

- README.md
- ember-cli-build.js
- tests/dummy/app/serializers/application.js
Add missing session setup configuration to dummy app to
adhere to upgrade guide v4 of ember-simple-auth. In addition,
fix defaultSerializer deprecation in dummy app adapter by adding
an application serializer in the dummy app.
> fix(dummy): correct session setup and fix serializer deprecation

- addon/routes/oidc-authentication.js
- tests/unit/routes/oidc-authentication-test.js
- tests/unit/services/session-test.js
Collect the attempted transition to route name and url. This
allows the correct redirect to the attempted transition after
a successful authentication.
> fix(authentication): fix collection of attempted transition url

- addon/authenticators/oidc.js
- addon/config.js
- addon/index.js
- addon/routes/oidc-authentication.js
- addon/services/session.js
- package.json
- tests/unit/authenticators/oidc-test.js
- tests/unit/routes/oidc-authentication-test.js
- yarn.lock
It's advised to always use `resolveRegistration` for getting the config object if the owner is accessible from the code which it is in our case. `ember-get-config` uses `@embroider/macros` to resolve the config which can lead to unexpected content and duplicated config objects in the code instead of the meta tag.
> fix(config): remove usage of ember-get-config

- addon/routes/oidc-authentication.js
- tests/unit/routes/oidc-authentication-test.js
Include the query parameters of the attempted transition
when storing the nextURL in the session storage. This ensures
that redirects after a successful login with the oidc provider
are performed correctly and don't result in 404 responses.
> fix(auth-route): store query params of attempted transition

- addon/apollo.js
- package.json
This is necessary since embroider doesn't handle optional dependencies properly as reported here: https://github.com/embroider-build/embroider/issues/1266
This commit makes `@apollo/client` temporarly a non optional dependency to fix the current issue we have in apps without that dependency. However, we need to revert this as soon as the issue above is resolved since we don't want to enforce this dependency.
Related to #597
> fix(apollo): make apollo client a dependency

- addon/services/session.js
- addon/unauthorized.js
Normally, you should handle `invalidateSession` events directly via the [`handleInvalidation`](https://github.com/mainmatter/ember-simple-auth/blob/ffa070ab6eb8a8907d2c549aedc0c6edd73a3300/packages/ember-simple-auth/addon/services/session.js#L369) method. [Some circumstance in the past](https://github.com/adfinis/ember-simple-auth-oidc/commit/628eecb77a518122b5c877cccf4fed2bcf279530#diff-e322dfc58f6dc338aaf40c1cdf9c5c55d702cf37b4ca713482ceb64f3ad2b3f0R38) motivated us to move it to `handleUnauthorized` and mute the default behavior of `handleInvalidation`. Meanwhile a lot of [things changed](https://github.com/mainmatter/ember-simple-auth/releases) and `ember-simple-auth` received some refactorings. Sadly the `handleInvalidation` hook is still not working out for us, since the session …
> fix: always reconnect on unauthorized responses

- addon/unauthorized.js
We have seen redirect loops when the refresh token expired and the authenticator tried to redirect to the initial route after a fresh token was acquired. 
The `handleUnauthorized` method is called on every unauthenticated request (`401` response). It will then trigger `invalidate` session and redirect to `/`.  Since a lot of requests can get triggered on `/` we have to defer the redirect for a while, to give the chance to redirect to the authentication route first, before other *failed* request would try to do the same. (*race condition*)
> fix: prevent redirect loops to login route

- README.md
- addon/config.js
- addon/unauthorized.js
When multiple requests failed with a `401` status, they would trigger reconnects to the auth endpoint. Sadly this created a race condition. While the first connection to the auth endpoint was made, another old request already failed with a `401` interrupting the previous auth request and the page would load anew beginning the cycle again. This is caused, by the [browser not canceling the commissioned fetch](https://stackoverflow.com/questions/8566222/javascript-window-redirect-doesnt-work-in-chrome-canceled-status/67992162#67992162) requests after the `location.replace(...)` call. The previous `next(...)` call was certainly not enough time for all the eventual requests to finish.
Now we *collect* all the failing requests in a 1 second timespan and redirect after that. This prevents the …
> fix: prevent race condition in unauthorized handler

- tests/dummy/mirage/config.js
I was getting an error about a missing `User` model because we weren't passing a necessary argument in `mirage/config.js`.
> Pass config.store to discoverEmberDataModels
